<!DOCTYPE html>
<html>
<head>
    <!-- Skal laves så den får fra admin -->
    <title>
        Control pannel
    </title>
    <meta charset="UTF-8"/>
    <!-- Css includes -->
    <link rel="stylesheet" href="/view/_generel/css/reset.css"/>
    <link rel="stylesheet" href="<?php echo $config["dir"]; ?>css/styles.css"/>
    <!-- Js includes -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="<?php echo $config["dir"]; ?>js/toolbox.js"></script>
</head>
<body>
        <?php
        //If a user isset, and the user is an admin user
        if($user["admin"] == 1){
            //Get the header layout
            include("layout/header.phtml");

            //Get the real content (Mostly from DB)
            include($writemaincontent);

            //Get the footer layout
            include("layout/footer.phtml");
        } else {
            //Tell the user to login with the login layout
            include("login.phtml");
        }
        ?>
</body>
</html>