<div id="loginBackground">

    <div class="wrapper">

        <h1>Login</h1>

        <form method="get">
            <div>
                <label for="username">Username</label>
                <input type="text" id="username" name="User-username"/>
                <label for="password">Password</label>
                <input type="password" id="password" name="User-password"/>
            </div>
            <input type="submit" name="Action-User-login" value="Let's do this"/>
        </form>

    </div>

</div>