<div id="loginBackground">

    <div class="wrapper">

        <h1>Login</h1>

        <div id="error" style="display: none;">
            <h1 style="font-size: 22px; color: #B54A52;">
                <?php echo $error["msg"]; ?>
            </h1>
        </div>

        <form method="post">
            <div>
                <label for="username">Username</label>
                <input type="text" id="username" autofocus="autofocus" name="User-username"/>
                <label for="password">Password</label>
                <input type="password" id="password" name="User-password"/>
            </div>
            <input type="submit" name="Action-User-login" value="Let's do this"/>
        </form>

        <script type="text/javascript">
            $(function() {
               <?php if(isset($error)) {
                ?>
                /* If Error We show error msg */
                setTimeout(function() {
                    $("#error").slideToggle();
                }, 250);
                <?php
                    }
                ?>
            });
        </script>

    </div>

</div>