<!DOCTYPE html>
<html>
<head>
    <!-- Skal laves så den får fra admin -->
    <title>
        Admin
    </title>
    <meta charset="UTF-8"/>
    <!-- Font Open Sans import -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'/>
    <!-- Css includes -->
    <link rel="stylesheet" href="/view/_generel/css/reset.css"/>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css"/>
    <link rel="stylesheet" href="<?php echo $config["dir"]; ?>css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $config["dir"]; ?>css/tabs.css"/>
    <link rel="stylesheet/less" type="text/css" href="<?php echo $config["dir"]; ?>css/styles.less"/>
    <!-- Js includes -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
    <script src="/view/_generel/js/less.js"></script>
    <script src="<?php echo $config["dir"]; ?>js/toolbox.js"></script>
</head>
<body>
        <?php
        //If a user isset, and the user is an admin user
        if($user["admin"] == 1){
            //Get the default layout
            include("default.phtml");
        } else {
            //Tell the user to login with the login layout
            include("login.phtml");
        }

        echo $include;
        ?>
</body>
</html>