<ul>
    <?php

    foreach($menu as $point) {
    ?>
        <li>
            <a href="/admin<?php echo $point["link"]; ?>">
                <i class="<?php echo $point["icon"]; ?>"></i><?php echo $point["title"]; ?>
            </a>
        </li>
    <?php
    }
    ?>
</ul>

<!-- Menu scrpt for active menu points -->
<script>
    $(document).ready(function() {

        var $url = window.location.pathname;

        $("nav ul li a").each(function() {
            if($(this).attr("href") == $url) {
                $(this).addClass("active");
                $(this).closest("li").addClass("active");
            }
        });

    });
</script>