<ul>
    <li>
        <a href="/admin">
            <i class="fa fa-pie-chart"></i>Dashboard
        </a>
    </li>
    <li>
        <a href="/admin/pages">
            <i class="fa fa-pagelines"></i> Pages
        </a>
    </li>
    <li>
        <a href="/admin/filearchive">
            <i class="fa fa-cloud"></i>File archive
        </a>
    </li>
    <li>
        <a href="/admin/settings">
            <i class="fa fa-plug"></i>Settings
        </a>
    </li>
</ul>

<!-- Menu scrpt for active menu points -->
<script>
    $(document).ready(function() {

        var $url = window.location.pathname;

        $("nav ul li a").each(function() {
            if($(this).attr("href") == $url) {
                $(this).addClass("active");
                $(this).closest("li").addClass("active");
            }
        });

    });
</script>